version: '2.4'
services:
    server:
        build:
            context: ../
            dockerfile: ./docker/Dockerfile
            target: dev
        ports: 
            - "5000:5000"
        volumes:
            - ../results:/src/results
            - ../upload:/src/upload
            - ../code:/src/code
        environment:
            # https://stackoverflow.com/a/51362214
            - PYTHONUNBUFFERED=1
            - DEBUG=true
            - MODULE
    ocr:
        image: ghcr.io/koralowiec/ocr-server:latest
        ports: 
            - "5001:5000"
        environment:
            - PYTHONUNBUFFERED=1