version: '2.4'
services:
    api:
        build:
            context: ../
            dockerfile: ./docker/gpu.Dockerfile
            target: dev
        # https://github.com/NVIDIA/nvidia-docker/wiki#do-you-support-docker-compose
        runtime: nvidia
        ports: 
            - "5000:5000"
        volumes:
            - ../results:/src/results
            - ../upload:/src/upload
            - /tmp/openimages_v4__ssd__mobilenet_v2:/model
            - ../code:/src/code
        environment:
            # https://stackoverflow.com/a/51362214
            - PYTHONUNBUFFERED=1
            - DEBUG=true